# Generated by Django 5.0.6 on 2024-08-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_citizenshipcountry_residentcountry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evisac',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evisar',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='traditionalvisac',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='traditionalvisar',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='visafreec',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='visafreer',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
