# Generated by Django 5.0.6 on 2024-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0004_countryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evisac',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='evisar',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='traditionalvisac',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='traditionalvisar',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='visafreec',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='visafreer',
            name='price_per_person',
        ),
        migrations.AddField(
            model_name='countryproduct',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
