# Generated by Django 5.0.6 on 2024-08-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0005_remove_evisac_price_per_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('textarea', 'Textarea'), ('upload', 'Upload')], max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.countryproduct')),
            ],
            options={
                'verbose_name_plural': 'Product Forms',
            },
        ),
    ]
