# Generated by Django 5.0.6 on 2024-08-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0006_countryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryproduct',
            name='visa_type',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('e_visa', 'E Visa'), ('visa_free', 'Visa Free')], default='e_visa', max_length=100),
            preserve_default=False,
        ),
    ]
