# Generated by Django 5.0.6 on 2024-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0008_countryformresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryformresponse',
            options={'verbose_name_plural': 'Visa Applications'},
        ),
        migrations.AlterField(
            model_name='countryformresponse',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
