# Generated by Django 5.0.6 on 2024-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0009_alter_countryformresponse_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryformresponse',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RemoveField(
            model_name='countryformresponse',
            name='field_label',
        ),
        migrations.RemoveField(
            model_name='countryformresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='countryformresponse',
            name='responses',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
