# Generated by Django 5.0.6 on 2024-08-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0010_rename_country_countryformresponse_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryformresponse',
            name='responses',
            field=models.JSONField(default=dict),
        ),
    ]
