# Generated by Django 5.0.6 on 2024-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0012_alter_countryformresponse_country_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evisac',
            name='active',
        ),
        migrations.RemoveField(
            model_name='evisar',
            name='active',
        ),
        migrations.RemoveField(
            model_name='traditionalvisac',
            name='active',
        ),
        migrations.RemoveField(
            model_name='traditionalvisar',
            name='active',
        ),
        migrations.RemoveField(
            model_name='visafreec',
            name='active',
        ),
        migrations.RemoveField(
            model_name='visafreer',
            name='active',
        ),
        migrations.AddField(
            model_name='countryformresponse',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='countryproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
