# Generated by Django 5.0.6 on 2024-08-21 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0013_remove_evisac_active_remove_evisar_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryformresponse',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
