# Generated by Django 5.0.6 on 2024-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0016_alter_userwishlist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryform',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
