# Generated by Django 5.0.6 on 2024-08-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0017_countryform_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryformresponse',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='countryformresponse',
            name='form_id',
            field=models.CharField(default='asasa', max_length=100),
            preserve_default=False,
        ),
    ]
