# Generated by Django 5.0.6 on 2024-09-14 19:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0020_countryproduct_description_rich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryproduct',
            name='description_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
