# Generated by Django 5.0.6 on 2024-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0021_alter_countryproduct_description_rich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryform',
            name='field_label',
            field=models.CharField(max_length=500),
        ),
    ]
