# Generated by Django 5.0.6 on 2024-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('menu_item_1', models.CharField(max_length=100)),
                ('menu_item_1_link', models.CharField(max_length=100)),
                ('menu_item_2', models.CharField(max_length=100)),
                ('menu_item_2_link', models.CharField(max_length=100)),
                ('menu_item_3', models.CharField(max_length=100)),
                ('menu_item_3_link', models.CharField(max_length=100)),
                ('menu_item_4', models.CharField(max_length=100)),
                ('menu_item_4_link', models.CharField(max_length=100)),
                ('menu_item_5', models.CharField(max_length=100)),
                ('menu_item_5_link', models.CharField(max_length=100)),
            ],
        ),
    ]
