# Generated by Django 5.0.6 on 2024-07-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_hero_alter_header_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_banner_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_banner_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_banner_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
