# Generated by Django 5.0.6 on 2024-07-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_hero_hero_banner_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='hero_image4',
        ),
    ]
