# Generated by Django 5.0.6 on 2024-07-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_hero_hero_banner_image4'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
            options={
                'verbose_name_plural': 'customerStories',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('footer_text_bottom', models.TextField(blank=True, null=True)),
                ('footer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('footer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link_linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link_youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link_whatsapp', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
