# Generated by Django 5.0.6 on 2024-07-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_category_contactform_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
