# Generated by Django 5.0.6 on 2024-08-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
