# Generated by Django 5.0.6 on 2024-10-05 18:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
