name: Deploy Django
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up environment
        run: |
          # Create virtual env if it doesn't exist
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn
            
      - name: Run migrations
        run: |
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput --clear
            
      - name: Restart server
        run: |
          # Kill any existing gunicorn processes
          pkill gunicorn || true
          # Start gunicorn in the background
          source venv/bin/activate
          nohup gunicorn --bind 0.0.0.0:8000 twh_project.wsgi > server.log 2>&1 &