name: Deploy Django
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    env:
      SECRET_KEY: django-insecure-your-secret-key-here
      DEBUG: True
      DATABASE_URL: postgresql://neondb_owner:npg_y7I6ksbmEATL@ep-empty-king-a8wh54nl-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
      STRIPE_SECRET_KEY: your_stripe_secret_key
      STRIPE_PUBLISHABLE_KEY: your_stripe_publishable_key
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up environment
        run: |
          # Create virtual env if it doesn't exist
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn
            
      - name: Run migrations
        run: |
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput --clear
            
      - name: Restart server
        run: |
          # Kill any existing gunicorn processes
          pkill gunicorn || true
          # Start gunicorn in the background
          source venv/bin/activate
          nohup gunicorn --bind 0.0.0.0:8000 twh_project.wsgi > server.log 2>&1 &